// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlLaT1G3KiwyvQ2nXbFpE3CbIEHpGUyHU',
    appId: '1:872489366835:web:d53e7bb7e5fedf70fa3a46',
    messagingSenderId: '872489366835',
    projectId: 'mywardrobeapp-5d31a',
    authDomain: 'mywardrobeapp-5d31a.firebaseapp.com',
    storageBucket: 'mywardrobeapp-5d31a.firebasestorage.app',
    measurementId: 'G-5VKD7HFZV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiPrx3PAUambYZ-aACzGyzOivwUV_xcls',
    appId: '1:872489366835:android:013f285348d0c98afa3a46',
    messagingSenderId: '872489366835',
    projectId: 'mywardrobeapp-5d31a',
    storageBucket: 'mywardrobeapp-5d31a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuo-22wgiEvi9J-ppX7gLP1y4lodj66QE',
    appId: '1:872489366835:ios:7db807078c298788fa3a46',
    messagingSenderId: '872489366835',
    projectId: 'mywardrobeapp-5d31a',
    storageBucket: 'mywardrobeapp-5d31a.firebasestorage.app',
    iosBundleId: 'com.example.homeAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuo-22wgiEvi9J-ppX7gLP1y4lodj66QE',
    appId: '1:872489366835:ios:7db807078c298788fa3a46',
    messagingSenderId: '872489366835',
    projectId: 'mywardrobeapp-5d31a',
    storageBucket: 'mywardrobeapp-5d31a.firebasestorage.app',
    iosBundleId: 'com.example.homeAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlLaT1G3KiwyvQ2nXbFpE3CbIEHpGUyHU',
    appId: '1:872489366835:web:0d2f9b6026c25951fa3a46',
    messagingSenderId: '872489366835',
    projectId: 'mywardrobeapp-5d31a',
    authDomain: 'mywardrobeapp-5d31a.firebaseapp.com',
    storageBucket: 'mywardrobeapp-5d31a.firebasestorage.app',
    measurementId: 'G-8WRNSGH27J',
  );
}
